Added AWS Postgres Config

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -73,25 +73,21 @@ jobs:
           ssh -i ssh_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pkill -f siita-server.jar"
       
 
-      - name: Start and Test the application
+      - name: Start the application
         run: |
           ssh -i ssh_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "nohup java -jar /home/ec2-user/apps/siita-server/github/workspace/target/siita-server.jar > /dev/null 2>&1 &"
-          # Test the application
-          url="http://${{ secrets.EC2_HOST }}:8008/health"
-          retries=10
-          wait_seconds=5
-      
-          for ((i=1; i<=$retries; i++)); do
-          response_code=$(curl --silent --output /dev/null --write-out "%{http_code}" "$url")
-          
-          if [ $response_code -eq 200 ]; then
-          echo "Application is running and healthy. HTTP Status Code: $response_code"
-          break
-          elif [ $i -eq $retries ]; then
-          echo "Application did not start properly. Last response code: $response_code"
-          exit 1
+
+      - name: Wait for the application to start
+        run: |
+          sleep 10 # Adjust the sleep time based on your application's startup time
+
+      - name: Test Application Health
+        run: |
+          response_code=$(ssh -i ssh_key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "curl -s -o /dev/null -w '%{http_code}' http://localhost:8008/health")
+
+          if [ "$response_code" -eq 200 ]; then
+            echo "Health check successful. Status code: $response_code"
           else
-          echo "Retrying in $wait_seconds seconds (Attempt $i/$retries)..."
-          sleep $wait_seconds
+            echo "Health check failed. Unexpected status code: $response_code"
+            exit 1
           fi
-          done
